---

- name: Get latest release metadata for AutoPkg and MunkiTools
  vars:
    autopkg_latest_meta: "{{ lookup('url', 'https://api.github.com/repos/autopkg/autopkg/releases/latest') }}"
    munki_latest_meta: "{{ lookup('url', 'https://api.github.com/repos/munki/munki/releases/latest') }}"

- name: Get latest release download url for AutoPkg and MunkiTools
  vars:
    autopkg_release_url: "{{ autopkg_latest_meta.assets.browser_download_url | from_json }}"
    munki_release_url: "{{ munki_latest_meta.assets.browser_download_url | from_json }}"

- name: Download latest AutoPkg and Munki releases
  get_url:
    url: "{{ item.url }}"
    dest: "{{ user_home }}/{{ item.name }}-latest.pkg"
  with-items:
    - autopkg:
        url: "{{ autopkg_release_url }}"
        name: autopkg
    - munki:
        url: "{{ munki_release_url }}"
        name: munki

- name: Install AutoPkg and Munki 
  shell:
    cmd: installer -verboseR -pkg {{ user_home }}/{{ item }}-latest.pkg -target /
    become: yes
  with-items:
    - autopkg
    - munki

- name: Clean-up Installer Packages
  shell:
    cmd: rm {{ user_home }}/{{ name }}-latest.pkg
  with-items:
    - autopkg
    - munki 
