---

- name: Install MunkiTools and AutoPkg on the target system
  block:
    - name: Get latest release metadata for AutoPkg and MunkiTools
      uri:
        url: https://api.gitbub.com/repos/{{ item.path }}/releases/latest
        register: "{{ item.name }}_latest_meta"

    - name: Download latest AutoPkg and Munki releases
      get_url:
        url: "{{ item.name }}_latest_meta.assets.browser_download_url | from_json"
        dest: "{{ item.name }}-latest.pkg"

    - name: Install AutoPkg and Munki 
      command:
        cmd: installer -verboseR -pkg {{ item.name }}-latest.pkg 
        become: yes

    - name: Clean-up Installer Packages
      file:
        state: absent
        path: "{{ item.name }}-latest.pkg" 

  with_items:
    - {name: munki, path: munki/munki}
    - {name: autopkg, path: auotpkg/autopkg, when: is_munki_admin == true}
