---

- name: Get latest release metadata for AutoPkg and MunkiTools
  uri:
    url: https://api.gitbub.com/repos/{{ item.path }}/releases/latest
    register: "{{ item.name }}_latest_meta"
  loop:
    - autopkg:
        name: autopkg
        path: autopkg/autopkg
    - munki:
        name: munki
        path: munki/munki

- name: Download latest AutoPkg and Munki releases
  get_url:
    url: "{{ item.url }}"
    dest: "{{ user_home }}/{{ item.name }}-latest.pkg"
  loop:
    - autopkg:
        url: "{{ autopkg_latest_mega.assets.browser_download_url | from_json }}"
        name: autopkg
    - munki:
        url: "{{ munki_latest_meta.assets.browser_download_url | from_json }}"
        name: munki

- name: Install AutoPkg and Munki 
  command:
    cmd: installer -verboseR -pkg {{ user_home }}/{{ item }}-latest.pkg -target /
    become: yes
  loop:
    - autopkg
    - munki

- name: Clean-up Installer Packages
  command:
    cmd: rm {{ user_home }}/{{ name }}-latest.pkg
  loop:
    - autopkg
    - munki 
