---

- name: Get latest release metadata for AutoPkg and MunkiTools
  uri:
    url: https://api.gitbub.com/repos/{{ core_packages.path }}/releases/latest
    register: "{{ core_packages.name }}_latest_meta"

- name: Download latest AutoPkg and Munki releases
  get_url:
    url: "{{ core_packages.file_src }}"
    dest: "{{ core_packages.file_dest }}"

- name: Install AutoPkg and Munki 
  command:
    cmd: installer -verboseR -pkg {{ core_packages.file_dest }} 
    become: yes

- name: Clean-up Installer Packages
  file:
    state: absent
    path: "{{ core_packages.file_dest }}" 
