---

- name: Clone Repo
  git:
    src: "{{ munkitools_repo_url }}"
    dest: "{{ munki_repo_loc }}" 
    when: "{{ munkitools_existing_repo == true }}"

- name: Create New Local Repo
  file:
     path: "{{ munki_repo_loc }}/{{ item }}"
     state: directory
     owner: "{{ munki_admin_user }}"
     mode: a+rX
     when: not munkitools_existing_repo
  loop:
       - catalogs
       - icons
       - manifests
       - pkgs
       - pkgsinfo

- name: Prep repo directories for syncing to cloud
  file:
    path: "{{ munki_repo_loc }}/{{ item }}"
    state: file
    owner: "{{ munki_admin_user }}"
    when: not munkitools_existing_repo
  loop:
    - catalogs/.miac
    - icons/.miac
    - manifests/.miac
    - pkgs/.miac
    - pkgsinfo/.miac

- name: Set Munki System Settings
  community.general.osx_defaults:
    domain: com.googlecode.munki.munkiimport
    key: "{{ item.key }}"
    type: string
    value: "{{ item.value }}"
  loop:
    - editor:
        key: "editor"
        value: "{{ munki_editor }}"
    - repo_path:
        key: "repo_path"
        value: "{{ munki_repo_loc }}"
    - pkginfo_extension:
        key: "pkginfo_extension"
        value: .plist
    - default_catalog:
        key: "default_catalog"
        value: "{{ munki_default_catalog }}"
