---

- name: Set-up AutoPkg for use with Munki
  community.general.osx_defaults:
    domain: com.github.autopkg
    key: MUNKI_REPO
    type: string
    value: "{{ munki_repo_loc }}"

- name: Add AutoPkg Repos
  shell:
    cmd: autopkg add {{ autopkg_repos }}

- name: Update AutoPkg Repos
  shell:
    cmd: autopkg repo-update {{ autopkg_repos }}

- name: Copy AutoPkg preferences for Admin User
  shell:
    cmd: plutil -convert xml1 ~/Library/Preferences/com.googlecode.munki.munkiimport.plist

- name: Add AutoPkg Packages
  shell:
    cmd: autopkg make-override {{ autopkg_packages }}
    cmd: autopkg update-trust-info {{ autopkg_packages }}
    cmd: run {{ autopkg_packages }}
