--

- name: Get AutoPkg Release Info
  get_url:
    url: https://api.github.com/repos/autopkg/autopkg/releases/latest
    register: release_info

- set_fact:
    release_json: "{{ release_info | from_json }}"

- name: Download AutoPkg Release
  get_url:
    url: "{{ release_url }}"
    with_dict: release_json.assetts.browser_download_url
    dest: ~/Downloads/autopkg-latest.pkg

- name: Install AutoPkg
  command: installer -pkg "~/Downloads/autopkg-latest.pkg" -target /
  become: yes

- name: Cleanup AutoPkg
  file:
    path: ~/Downloads/autopkg-latest.pkg
    state: absent

- name: Install Munki using AutoPkg
  command: autopkg install munkitools.install
  become: yes

- name: Clone Existing Munki Repo

- name: Set-up New Munki Repo

