---

- name: Clone Repo
  git_clone:
    src: "{{ munkitools_repo_url }}"
    dest: "{{ munki_repo_loc }}" 
    when: munkitools_existing_repo

- name: Create New Local Repo
  file:
     path: "{{ munki_repo_loc }}/{{ item }}"
     state: directory
     owner: "{{ munki_admin_user }}"
     mode: a+rX
     when: not munkitools_existing_repo
  with_items:
       - catalogs
       - icons
       - manifests
       - pkgs
       - pkgsinfo

- name: Prep repo directories for syncing to cloud
  file:
    path: "{{ munki_repo_loc }}/{{ item }}"
    state: file
    owner: "{{ munki_admin_user }}"
    when: not munkitools_existing_repo
  with_items:
    - catalogs/.miac
    - icons/.miac
    - manifests/.miac
    - pkgs/.miac
    -pkgsinfo/.miac

- name: Set Munki System Settings
  community.general.osx_defaults:
    domain: com.googlecode.munki.munkiimport
    key: "{{ item.key }}"
    type: string
    value: "{{ item.value }}"
  with-items:
    - editor:
        key: "editor"
        value: "{{ munki_editor }}"
    - repo_path:
        key: "repo_path"
        value: "{{ munki_repo_loc }}"
    - pkginfo_extension:
        key: "pkginfo_extension"
        value: .plist
    - default_catalog:
        key: "default_catalog"
        value: "{{ munki_default_catalog }}"

- name: Munki Make Catalogs
  - command: /usr/local/munki/makecatalogs {{ munki_repo_loc }}

- name: Create Site Default Manifest
  - command: /usr/local/munki/manifestutil new-manifest site_default

- name: Add Default Catalog to Default Manifest
  - command: /usr/local/munki/manifestutil add-catalog {{ munki_default_catalog }} --manifest site_default

- name: Identify Packages for Default Catalog
  - command: /usr/local/munki/manifestutil list-catalog-items {{ munki_default_catalog }}
    register: packages_for_catalog

- name: Add Packages to Default Catalog
  - command: /usr/local/munki/manifestutil add-pkg {{ item }} --manifest site_default
  loop: {{ packages_for_catalog }}
